apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: repositories  
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/core
  prune: true