apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: core  
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure
  prune: true
  wait: true
  timeout: 5m    