apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-2
  namespace: flux-system
spec:
  interval: 60m0s
  prune: true
  force: true # recreate resources on immutable fields changes
  wait: true
  timeout: 5m    
  retryInterval: 2m
  #dependsOn:
    #- name: infrastructure-1  
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure-2