apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: repositories
  namespace: flux-system
spec:
  interval: 60m0s
  prune: true
  force: true # recreate resources on immutable fields changes
  wait: true
  timeout: 5m    
  retryInterval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/cluster/repositories