---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-release
  namespace: flux-system
spec:
  interval: 12h
  targetNamespace: nfs
  chart:
    spec:
      chart: rook-ceph-cluster
      version: '>=0.0.0'
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 12h