---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-ceph-crds
spec:
  interval: 15m
  prune: false
  sourceRef:
    kind: GitRepository
    name: rook-ceph-source