---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: sonarr
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`sonarr.mushroomkingdom.io`)
      services:
        - name: sonarr
          port: 8989