---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: flux-system
spec:
  interval: 12h
  targetNamespace: sonarr
  releaseName: sonarr
  chart:
    spec:
      chart: sonarr    
      version: '>=0.0.0'
      sourceRef:
        kind: HelmRepository
        name: sonarr
        namespace: flux-system
      interval: 12h
  values:
    env:
      TZ: "America/New_York"
    image:
      tag: "v3.0.8.1507"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568      
    persistence:
      config:
        enabled: true
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.1.12
            path: /volume1/NAS
        mountPath: /NAS