---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mayastor
spec:
  interval: 15m
  prune: false
  sourceRef:
    kind: GitRepository
    name: mayastor
    namespace: flux-system