---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mayastor-control-plane
spec:
  interval: 15m
  prune: false
  path: /deploy
  sourceRef:
    kind: GitRepository
    name: mayastor-control-plane
    namespace: flux-system