---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: flux-system
spec:
  interval: 12h
  targetNamespace: rook-ceph
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.9.4
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 12h
  values:
    toolbox:
      enabled: false      
    dashboard:
      enabled: true
      ssl: false  
    resources:
      mgr:
        limits:
          cpu: "250m" # "1000m"
          memory: "256Mi" # "1Gi"
        requests:
          cpu: "100m" # "500m"
          memory: "100Mi" # "512Mi"
      mon:
        limits:
          cpu: "500m" # "2000m"
          memory: "500Mi" # "2Gi"
        requests:
          cpu: "250m" # "1000m"
          memory: "256Mi" # "1Gi"
      osd:
        limits:
          cpu: "500m" # "2000m"
          memory: "1Gi" # "4Gi"
        requests:
          cpu: "250m" # "1000m"
          memory: "1Gi" # "4Gi"
      prepareosd:
        limits:
          cpu: "250" # "500m"
          memory: "100Mi" # "200Mi"
        requests:
          cpu: "100m" # "500m"
          memory: "50Mi"
      mgr-sidecar:
        limits:
          cpu: "250m" # "500m"
          memory: "100Mi"
        requests:
          cpu: "100m"
          memory: "40Mi"
      crashcollector:
        limits:
          cpu: "250m" # "500m"
          memory: "60Mi"
        requests:
          cpu: "100m"
          memory: "60Mi"
      logcollector:
        limits:
          cpu: "250m" # "500m"
          memory: "256Mi" # "1Gi"
        requests:
          cpu: "100m"
          memory: "100Mi"
      cleanup:
        limits:
          cpu: "256m" # "500m"
          memory: "256Mi" # "1Gi"
        requests:
          cpu: "100m" # "500m"
          memory: "100Mi"
