---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 12h
  targetNamespace: prometheus
  chart:
    spec:
      chart: prometheus      
      version: '>=0.12.1'
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 12h
  values: