kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mayastor-3
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  repl: '3'
  protocol: 'nvmf'
  ioTimeout: '60'
  local: 'true'
provisioner: io.openebs.csi-mayastor
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer