

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  interval: 12h
  targetNamespace: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      version: '>=0.0.0'
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 12h
  values:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 256Mi    