

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  interval: 12h
  targetNamespace: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      version: v1.9.4
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 12h
  values:
    crds:
      enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    csi:
      enableRbdDriver: true
      enableCephfsDriver: false        