---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 12h
  targetNamespace: longhorn-system
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn    
      version: '>=0.0.0'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 12h
  values:
    defaultSettings:
      defaultReplicaCount: 3
      defaultDataPath: /storage/
      backupTarget: nfs://192.168.1.12:/volume1/NAS/Backups/longhorn
    persistence:
      defaultFsType: xfs