---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: flux-system
spec:
  interval: 12h
  targetNamespace: radarr
  releaseName: radarr
  chart:
    spec:
      chart: radarr    
      version: '>=0.0.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 12h
  values:
    env:
      TZ: "America/New_York"
    image:
      tag: "v4.1.0.6175"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568      
    persistence:
      config:
        enabled: true
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.1.12
            path: /volume1/NAS
        mountPath: /NAS