---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: flux-system
spec:
  interval: 12h
  targetNamespace: sabnzbd
  releaseName: sabnzbd
  chart:
    spec:
      chart: sabnzbd    
      version: '>=0.0.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 12h
  values:
    image:
      tag: "v3.5.3"
    env:
      TZ: "America/New_York"
      HOST_WHITELIST_ENTRIES: >-
        sabnzbd.mushroomkingdom.io
    persistence:
      config:
        enabled: true
      #media:
        #enabled: true
        #type: custom
        #volumeSpec:
          #nfs:
            #server: 192.168.1.12
            #path: /volume1/NAS
        #mountPath: /NAS
    podSecurityContext:
      supplementalGroups:
        - 568