---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  namespace: sabnzbd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mayastor-3
  resources:
    requests:
      storage: 1Gi