---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: mayastor
  namespace: flux-system  
spec:
  interval: 30m
  url: https://github.com/openebs/mayastor.git
  ref:
    tag: v1.0.1
  ignore: |
    # exclude all
    /*
    # path to crds
    !/cluster/examples/kubernetes/ceph/crds.yaml