---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: mayastor
  namespace: flux-system  
spec:
  interval: 30m
  url: https://github.com/openebs/mayastor.git
  ref:
    tag: v1.0.1
  ignore: |
    # exclude all
    /*
    # except
    !/deploy/nats-deployment.yaml
    !/deploy/etcd/storage/localpv.yaml
    !/deploy/etcd/statefulset.yaml 
    !/deploy/etcd/svc.yaml
    !/deploy/etcd/svc-headless.yaml
    !/deploy/csi-daemonset.yaml
    !/deploy/mayastor-daemonset.yaml

