---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: mayastor
  namespace: flux-system  
spec:
  interval: 30m
  url: https://github.com/openebs/mayastor.git
  ref:
    tag: v1.0.1
  include:
    - repository:
        name: other-repository      
      url: https://github.com/openebs/mayastor-control-plane.git
      ref:
        tag: v1.0.1      
      fromPath: /deploy/
      toPath: mayastor-control-plane
  ignore: |
    # exclude all
    /*
    # except
    !/deploy/nats-deployment.yaml
    !/deploy/etcd/storage/localpv.yaml
    !/deploy/etcd/statefulset.yaml 
    !/deploy/etcd/svc.yaml
    !/deploy/etcd/svc-headless.yaml
    !/deploy/csi-daemonset.yaml
    !/deploy/mayastor-daemonset.yaml

    !/mayastor-control-plane/deploy/operator-rbac.yaml
    !/mayastor-control-plane/deploy/mayastorpoolcrd.yaml
    !/mayastor-control-plane/deploy/core-agents-deployment.yaml
    !/mayastor-control-plane/deploy/csi-deployment.yaml
    !/mayastor-control-plane/deploy/msp-deployment.yaml    

