---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 12h
  targetNamespace: traefik
  chart:
    spec:
      chart: traefik     
      version: '>=0.0.0'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 12h
  values:
    providers:
      kubernetesIngress:
        enabled: false
    logs:
      general:
        level: ERROR
      access:
        enabled: false   