---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 12h
  targetNamespace: grafana
  chart:
    spec:
      chart: grafana      
      version: '>=0.0.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  values:
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-prometheus-server.prometheus.10.96.103.184
          access: proxy
          isDefault: true
    strongpassword: Password1!